{% set name = "pynng" %}
{% set version = "0.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pynng-{{ version }}.tar.gz
  sha256: 5edd3ccbeda2264d750d81533a11d45b5efbf8d99da65ba1f4569636f0eb9b70

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [win]

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
  host:
    - cffi
    - pip
    - pytest-runner
    - python
  run:
    - cffi
    - python
    - sniffio

test:
  imports:
    - pynng
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/codypiersall/pynng
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Python bindings for Nanomsg Next Generation.
  description: |
    Ergonomic bindings for nanomsg next generation (nng), in Python. pynng
    provides a nice interface on top of the full power of nng. nng, and
    therefore pynng, make it easy to communicate between processes on a
    single computer or computers across a network. This library is
    compatible with Python ≥ 3.5. nng is the rewriting of Nanomsg, which
    is the spiritual successor to ZeroMQ.
  doc_url: https://pynng.readthedocs.io/
  dev_url: https://github.com/codypiersall/pynng

extra:
  recipe-maintainers:
    - jan-janssen
