{% set name = "pynng" %}
{% set version = "0.7.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pynng-{{ version }}.tar.gz
  sha256: 6e4c8ea80d61d907d005ff29d58a34f7a23b320d4567b869a699f2b6329905e0

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [osx]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cffi                                   # [build_platform != target_platform]
    - cmake
    - {{ compiler('c') }}
    - ninja
    - make  # [unix]
  host:
    - cffi
    - pip
    - pytest-runner
    - python
  run:
    - cffi
    - python
    - sniffio

test:
  imports:
    - pynng
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/codypiersall/pynng
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Python bindings for Nanomsg Next Generation.
  description: |
    Ergonomic bindings for nanomsg next generation (nng), in Python. pynng
    provides a nice interface on top of the full power of nng. nng, and
    therefore pynng, make it easy to communicate between processes on a
    single computer or computers across a network. This library is
    compatible with Python ≥ 3.5. nng is the rewriting of Nanomsg, which
    is the spiritual successor to ZeroMQ.
  doc_url: https://pynng.readthedocs.io/
  dev_url: https://github.com/codypiersall/pynng

extra:
  recipe-maintainers:
    - jan-janssen
    - carlodri
